global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook-log'

receivers:
  - name: 'webhook-log'
    webhook_configs:
      - url: 'http://app:3000/alert-webhook'
        send_resolved: true
